import {
  BUTTON_TEXT_FIELD,
  DESCRIPTION_FIELD,
  IMAGE_FIELD,
  RATE_FIELD,
  TEXT_FIELD,
  TITLE_FIELD,
} from '@constants/fields';
import { TYPES } from '../types';

export const TYPE_FIELDS = {
  [TYPES[0].value]: [TITLE_FIELD, DESCRIPTION_FIELD, IMAGE_FIELD],
  [TYPES[1].value]: [TITLE_FIELD, DESCRIPTION_FIELD, IMAGE_FIELD],
  [TYPES[2].value]: [TITLE_FIELD, DESCRIPTION_FIELD, RATE_FIELD],
  [TYPES[3].value]: [TITLE_FIELD, DESCRIPTION_FIELD, IMAGE_FIELD],
  [TYPES[4].value]: [TITLE_FIELD, DESCRIPTION_FIELD, IMAGE_FIELD, BUTTON_TEXT_FIELD],
  [TYPES[5].value]: [TITLE_FIELD, DESCRIPTION_FIELD, IMAGE_FIELD],
  [TYPES[6].value]: [TITLE_FIELD, DESCRIPTION_FIELD, IMAGE_FIELD],
  [TYPES[7].value]: [TITLE_FIELD, TEXT_FIELD],
};
