import { BUTTON_TEXT_FIELD, DESCRIPTION_FIELD, RICH_CONTENT_FIELD, TEXT_FIELD, TITLE_FIELD } from '@constants/fields';
import { TYPES } from '../types';

export const TYPE_FIELDS = {
  [TYPES[0].value]: [TEXT_FIELD],
  [TYPES[1].value]: [TITLE_FIELD, DESCRIPTION_FIELD],
  [TYPES[2].value]: [DESCRIPTION_FIELD],
  [TYPES[3].value]: [RICH_CONTENT_FIELD],
  [TYPES[4].value]: [TITLE_FIELD, DESCRIPTION_FIELD],
  [TYPES[5].value]: [TITLE_FIELD, DESCRIPTION_FIELD, BUTTON_TEXT_FIELD],
  [TYPES[6].value]: [RICH_CONTENT_FIELD],
  [TYPES[7].value]: [TITLE_FIELD, DESCRIPTION_FIELD],
  [TYPES[8].value]: [TITLE_FIELD, DESCRIPTION_FIELD],
  [TYPES[9].value]: [TITLE_FIELD, DESCRIPTION_FIELD],
  [TYPES[10].value]: [TITLE_FIELD, DESCRIPTION_FIELD],
};
